spring.application.name=backend

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/sdms}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sdms_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:sdms_pass}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=true

server.port=8080